name: DeGray  # Choose your environment name
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
  - bioconda
dependencies:
  - pip
  - dlib=19.24.2
  - lmdb
  - numpy=1.24.3
  - opencv=4.7.0
  - ffmpeg=5.1.2
  - pillow=10.1.0
  - python_abi
  - libjpeg-turbo
  - jpeg
  - pyyaml=6.0.1
  - requests=2.31.0
  - scipy=1.9.1
  - timm=0.9.2
  - pytorch=2.2.0
  - torchvision=0.17.0
  - tqdm=4.65.0
  - wandb=0.15.5
  - scikit-image=0.22.0
  - tensorboard=2.15.1